name: ktlint

on: [ pull_request ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: minjunkweon/action-ktlint-auto-review@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
